// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'create_user_model.g.dart';

@JsonSerializable()
class CreateUserModel {
  final String? name;
  final String? email;
  final String? password;
  final String? retryPassword;
  final String? birthDay;

  CreateUserModel({
    required this.name,
    required this.email,
    required this.password,
    required this.retryPassword,
    required this.birthDay,
  });

  factory CreateUserModel.fromJson(Map<String, dynamic> json) =>
      _$CreateUserModelFromJson(json);

  Map<String, dynamic> toJson() => _$CreateUserModelToJson(this);
}
