// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

part 'dynamic_post_data.g.dart';

@JsonSerializable()
class DynamicPostData {
  final int totalLikes;
  final bool likedByMe;
  final int totalComments;

  DynamicPostData({
    required this.totalLikes,
    required this.likedByMe,
    required this.totalComments,
  });

  factory DynamicPostData.fromJson(Map<String, dynamic> json) =>
      _$DynamicPostDataFromJson(json);

  Map<String, dynamic> toJson() => _$DynamicPostDataToJson(this);
}
