// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';

import 'user.dart';

part 'post.g.dart';

// Generated by https://quicktype.io

@JsonSerializable()
class ShowPost {
  ShowPostModel showPostModel;
  User user;

  ShowPost({
    required this.showPostModel,
    required this.user,
  });

  factory ShowPost.fromJson(Map<String, dynamic> json) =>
      _$ShowPostFromJson(json);

  Map<String, dynamic> toJson() => _$ShowPostToJson(this);
}

@JsonSerializable()
class ShowPostModel {
  String id;
  String userId;
  String created;
  String? name;
  List<String>? attaches;
  int totalLikes;
  bool likedByMe;
  int totalComments;

  ShowPostModel({
    required this.id,
    required this.userId,
    required this.created,
    this.name,
    this.attaches,
    required this.totalLikes,
    required this.likedByMe,
    required this.totalComments,
  });

  factory ShowPostModel.fromJson(Map<String, dynamic> json) =>
      _$ShowPostModelFromJson(json);

  Map<String, dynamic> toJson() => _$ShowPostModelToJson(this);
}

@JsonSerializable()
class FullPost {
  ShowPostModel showPostModel;
  User user;
  List<ShowCommentModel> showCommentModels;

  FullPost({
    required this.showPostModel,
    required this.user,
    required this.showCommentModels,
  });

  factory FullPost.fromJson(Map<String, dynamic> json) =>
      _$FullPostFromJson(json);

  Map<String, dynamic> toJson() => _$FullPostToJson(this);
}

@JsonSerializable()
class ShowCommentModel {
  String id;
  String name;
  String message;
  String created;
  String avatarLink;

  ShowCommentModel({
    required this.id,
    required this.name,
    required this.message,
    required this.created,
    required this.avatarLink,
  });

  factory ShowCommentModel.fromJson(Map<String, dynamic> json) =>
      _$ShowCommentModelFromJson(json);

  Map<String, dynamic> toJson() => _$ShowCommentModelToJson(this);
}
